export const VEHICLE_BRANDS = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "BYD",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dacia",
  "Daihatsu",
  "Daewoo",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Geely",
  "Genesis",
  "GMC",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lotus",
  "Lada",
  "Mahindra",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "NIO",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "Rimac",
  "Rolls-Royce",
  "Saab",
  "Seat",
  "Skoda",
  "Subaru",
  "Suzuki",
  "Tata",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const VEHICLE_MODELS = {
  Acura: ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX", "ZDX"],
  "Alfa Romeo": ["4C", "Giulia", "Stelvio", "Tonale", "Junior"],
  "Aston Martin": ["DB11", "DBS", "DBX", "Vantage", "Valhalla", "Valkyrie"],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "e-tron",
    "e-tron GT",
    "TT",
    "R8",
  ],
  Bentley: ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  BMW: [
    "1 Series",
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "M3",
    "M4",
    "M5",
    "XM",
  ],
  Bugatti: ["Chiron", "Divo", "Veyron", "Bolide"],
  Buick: ["Enclave", "Encore", "Envision", "Regal"],
  BYD: ["Han", "Tang", "Yuan", "Dolphin", "Seal", "Atto 3"],
  Cadillac: ["CT4", "CT5", "Escalade", "Lyriq", "XT4", "XT5", "XT6"],
  Chevrolet: [
    "Blazer",
    "Camaro",
    "Corvette",
    "Cruze",
    "Equinox",
    "Malibu",
    "Silverado",
    "Spark",
    "Suburban",
    "Tahoe",
    "Trailblazer",
    "Traverse",
  ],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Citroen: [
    "Berlingo",
    "C3",
    "C4",
    "C5",
    "C5 Aircross",
    "Cactus",
    "DS3",
    "DS4",
    "DS5",
  ],
  Dacia: ["Duster", "Logan", "Sandero", "Spring", "Jogger"],
  Daihatsu: ["Mira", "Move", "Tanto", "Terios"],
  Daewoo: ["Lanos", "Matiz", "Nubira"],
  Dodge: ["Challenger", "Charger", "Durango", "Hornet", "Viper"],
  Ferrari: [
    "488",
    "812 Superfast",
    "F8 Tributo",
    "Portofino",
    "Roma",
    "SF90 Stradale",
    "Purosangue",
  ],
  Fiat: ["500", "500L", "500X", "Doblo", "Egea", "Panda", "Tipo"],
  Ford: [
    "Bronco",
    "EcoSport",
    "Edge",
    "Escape",
    "Explorer",
    "F-150",
    "Fiesta",
    "Focus",
    "Kuga",
    "Mondeo",
    "Mustang",
    "Puma",
    "Ranger",
    "Tourneo",
  ],
  Geely: ["Atlas", "Coolray", "Emgrand", "Geometry C"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  GMC: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "HR-V",
    "Jazz",
    "Legend",
    "Pilot",
    "Ridgeline",
    "ZR-V",
  ],
  Hummer: ["H2", "H3", "EV"],
  Hyundai: [
    "Accent",
    "Elantra",
    "i10",
    "i20",
    "i30",
    "IONIQ 5",
    "IONIQ 6",
    "Kona",
    "Palisade",
    "Santa Fe",
    "Sonata",
    "Tucson",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  Isuzu: ["D-Max", "MU-X", "Trooper"],
  Jaguar: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "XJ"],
  Jeep: [
    "Avenger",
    "Cherokee",
    "Compass",
    "Grand Cherokee",
    "Renegade",
    "Wrangler",
  ],
  Kia: [
    "Ceed",
    "Cerato",
    "EV6",
    "EV9",
    "Niro",
    "Optima",
    "Picanto",
    "Rio",
    "Seltos",
    "Sorento",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  Koenigsegg: ["Agera", "Jesko", "Regera"],
  Lamborghini: ["Aventador", "Huracan", "Urus", "Revuelto"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: ["CT", "ES", "GS", "IS", "LC", "LS", "NX", "RC", "RX", "UX"],
  Lotus: ["Elise", "Emira", "Evora", "Eletre"],
  Lada: ["Granta", "Niva", "Vesta"],
  Mahindra: ["Scorpio", "Thar", "XUV500", "XUV700"],
  Maserati: ["Ghibli", "GranTurismo", "Levante", "Quattroporte", "MC20"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-9", "MX-5"],
  McLaren: ["540C", "570S", "720S", "Artura", "P1"],
  "Mercedes-Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "CLA",
    "CLS",
    "E-Class",
    "EQS",
    "G-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "S-Class",
    "V-Class",
    "AMG GT",
  ],
  Mini: ["Clubman", "Convertible", "Cooper", "Countryman", "Hardtop"],
  Mitsubishi: [
    "ASX",
    "Eclipse Cross",
    "L200",
    "Outlander",
    "Pajero",
    "Space Star",
  ],
  NIO: ["ES6", "ES8", "ET5", "ET7"],
  Nissan: [
    "Altima",
    "Ariya",
    "Juke",
    "Leaf",
    "Micra",
    "Navara",
    "Note",
    "Qashqai",
    "X-Trail",
    "Z",
  ],
  Opel: ["Astra", "Corsa", "Crossland", "Grandland", "Insignia", "Mokka"],
  Peugeot: ["108", "2008", "208", "3008", "308", "5008", "508", "Partner"],
  Porsche: [
    "911",
    "Boxster",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  Renault: [
    "Arkana",
    "Austral",
    "Captur",
    "Clio",
    "Kadjar",
    "Kangoo",
    "Megane",
    "Talisman",
    "Twingo",
    "Zoe",
  ],
  Rimac: ["C_Two", "Nevera"],
  "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre"],
  Saab: ["9-3", "9-5"],
  Seat: ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"],
  Skoda: [
    "Enyaq",
    "Fabia",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Octavia",
    "Scala",
    "Superb",
  ],
  Subaru: ["Ascent", "Forester", "Impreza", "Legacy", "Outback", "XV"],
  Suzuki: ["Baleno", "Ignis", "Jimny", "Swift", "SX4", "Vitara"],
  Tata: ["Harrier", "Nexon", "Safari", "Tiago"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  Toyota: [
    "Auris",
    "Avensis",
    "bZ4X",
    "C-HR",
    "Camry",
    "Corolla",
    "GR86",
    "Hilux",
    "Land Cruiser",
    "Mirai",
    "Prius",
    "RAV4",
    "Supra",
    "Yaris",
  ],
  Volkswagen: [
    "Arteon",
    "Golf",
    "ID.3",
    "ID.4",
    "Jetta",
    "Passat",
    "Polo",
    "T-Cross",
    "T-Roc",
    "Tiguan",
    "Touareg",
  ],
  Volvo: ["C40", "S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90"],
};

export const VEHICLE_YEARS = Array.from({ length: 30 }, (_, i) =>
  (new Date().getFullYear() - i).toString()
);

export const FUEL_TYPES = [
  "Gasoline",
  "Diesel",
  "Hybrid",
  "Plug-in Hybrid",
  "Electric",
  "LPG",
  "CNG",
  "Hydrogen",
  "Biofuel",
];
